<NumberGenerator>:
    random_number_label: random_number_label

    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "Training App"
            font_size: 64
            color: 0.92, 0.45, 0, 1
        Label:
            id: random_number_label
            text: "-"
            font_size: 64
        Button:
            text: "Generate"
            font_size: 32
            size: 100, 50
            on_press: root.generate_number()